### ISSUE TITLE
Add TERM signal handling

### ISSUE THREAD

**Issue by matejhasul** [kbudde/rabbitmq_exporter#137]
I've started exported according to howto:
```
docker run -d -e RABBITMQ_NODENAME=my-rabbit --name my-rabbit -p 9419:9419 rabbitmq:3-management
docker run -d --net=container:my-rabbit kbudde/rabbitmq-exporter
```
Container is started and runs as expected:
```
[hasul@kra ~]$ docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                                         NAMES
e5afbe1709ad        kbudde/rabbitmq-exporter   "/app"                   5 seconds ago       Up 4 seconds                                                                                      objective_zhukovsky
4cad5848fe87        rabbitmq:3-management      "docker-entrypoint.s…"   15 seconds ago      Up 11 seconds       4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp, 0.0.0.0:9419->9419/tcp   my-rabbit

[hasul@kra ~]$ docker logs objective_zhukovsky
time="2019-07-31T08:42:50Z" level=info msg="Using default certificate pool"
time="2019-07-31T08:42:50Z" level=info msg="Starting RabbitMQ exporter" BRANCH=master BUILD_DATE="20190517-20:51:04" REVISION=a9ded1ded0fc9b049e8e633b303588518c18e3e8 VERSION=1.0.0-RC6.1
time="2019-07-31T08:42:50Z" level=info msg="Active Configuration" CAFILE=ca.pem EXCLUDE_METRICS="[]" INCLUDE_QUEUES=".*" INCLUDE_VHOST=".*" MAX_QUEUES=0 OUTPUT_FORMAT=TTY PUBLISH_ADDR= PUBLISH_PORT=9419 RABBIT_CAP
ABILITIES="no_sort,bert" RABBIT_EXPORTERS="[exchange node overview queue]" RABBIT_TIMEOUT=30 RABBIT_URL="http://127.0.0.1:15672" RABBIT_USER=guest SKIPVERIFY=false SKIP_QUEUES="^$" SKIP_VHOST="^$"
```
When I try to stop the container (AKA send TERM signal to the process) it is stopped with non-zero return code:
```
[hasul@kra ~]$ docker stop objective_zhukovsky
objective_zhukovsky

[hasul@kra ~]$ echo $?
2

[hasul@kra ~]$ docker inspect objective_zhukovsky | jq -r '.[].State'                                                                                                                                                 
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 2,
  "Error": "",
  "StartedAt": "2019-07-31T08:42:50.183008124Z",
  "FinishedAt": "2019-07-31T08:43:21.931817218Z"
}
```
Could you please correctly handle TERM signal?

**Comment by kbudde** [comment]
Fix was merged to master branch

**Comment by matejhasul** [comment]
Thanks!

**Comment by matejhasul** [comment]
IMHO it still does not work. `docker stop` returns 0 which is fine, but container itself finished with exitcode 2:
```
✔ kra:~/git/rabbitmq_exporter [master|✔]> make docker
>> building docker image                                                                                                                                                                                            
Sending build context to Docker daemon  14.08MB                                                                                                                                                                     
Step 1/17 : ARG GO_VERSION=1.13                 
Step 2/17 : FROM golang:${GO_VERSION}-alpine AS builder
.
.
.
Successfully built 7f57120f368a
Successfully tagged rabbitmq-exporter:master

✔ kra:~/git/rabbitmq_exporter [master|✔]>  docker run -d -e RABBITMQ_NODENAME=my-rabbit --name my-rabbit -p 9419:9419 rabbitmq:3-management
31cde815b29239275a96075843da76d16bf6a57ef7713a4c0d530ed0a9fadb3d
✔ kra:~/git/rabbitmq_exporter [master|✔]> docker run -d --net=container:my-rabbit rabbitmq-exporter:master
d996d94d22dec37d352217d338fcdf4072080d8349763be0b708a005e3269a81
✔ kra:~/git/rabbitmq_exporter [master|✔]> docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                                                                         NAMES
d996d94d22de        rabbitmq-exporter:master   "/app"                   5 seconds ago       Up 3 seconds                                                                                      nifty_blackwell
31cde815b292        rabbitmq:3-management      "docker-entrypoint.s…"   24 seconds ago      Up 22 seconds       4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp, 0.0.0.0:9419->9419/tcp   my-rabbit
✔ kra:~/git/rabbitmq_exporter [master|✔]> docker stop nifty_blackwell
nifty_blackwell
✔ kra:~/git/rabbitmq_exporter [master|✔]> echo $?
0
✔ kra:~/git/rabbitmq_exporter [master|✔]> docker inspect nifty_blackwell | jq -r '.[].State'
{
  "Status": "exited",
  "Running": false,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 0,
  "ExitCode": 2,
  "Error": "",
  "StartedAt": "2019-09-19T08:14:10.236302199Z",
  "FinishedAt": "2019-09-19T08:14:21.437837756Z"
}
```

**Comment by kbudde** [comment]
added sigterm to handled signals.
Docker exitcode is now 0.

**Comment by matejhasul** [comment]
Thanks, works as expected now.
